-- M5: retention — referral and share codes, onboarding, access grants and
-- the lifecycle-email ledger.
--
-- Generated by drizzle-kit and kept as generated: unlike 0002, every
-- change here is additive. The four user columns are nullable, so no
-- table is rebuilt, and the two unique indexes are safe on existing rows
-- because SQLite treats NULLs as distinct — every account may sit at NULL
-- and only issued codes have to be unique.

CREATE TABLE `access_grants` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`reason` text NOT NULL,
	`plan` text DEFAULT 'monthly' NOT NULL,
	`days` integer NOT NULL,
	`expires_at` integer NOT NULL,
	`source_user_id` text,
	`note` text DEFAULT '' NOT NULL,
	`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `access_grants_user_idx` ON `access_grants` (`user_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `access_grants_pair_idx` ON `access_grants` (`user_id`,`reason`,`source_user_id`);--> statement-breakpoint
CREATE TABLE `email_log` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`kind` text NOT NULL,
	`window` text NOT NULL,
	`sent_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `email_log_user_idx` ON `email_log` (`user_id`,`kind`);--> statement-breakpoint
ALTER TABLE `users` ADD `referral_code` text;--> statement-breakpoint
ALTER TABLE `users` ADD `referred_by` text;--> statement-breakpoint
ALTER TABLE `users` ADD `share_code` text;--> statement-breakpoint
ALTER TABLE `users` ADD `onboarded_at` integer;--> statement-breakpoint
CREATE UNIQUE INDEX `users_referral_code_idx` ON `users` (`referral_code`);--> statement-breakpoint
CREATE UNIQUE INDEX `users_share_code_idx` ON `users` (`share_code`);