import type { Subtopic } from "../../lib/taxonomy.ts";
import { conceptId, entityId, sourceIdeaId } from "./ids.ts";
import type { ConceptRecord } from "./types.ts";

export const PILOT_SUBTOPICS = [
  "exponents_roots_properties",
  "algebraic_translation",
  "probability",
] as const satisfies readonly Subtopic[];

const E = {
  combine: conceptId("exponents_roots_properties", "same-base exponent combination"),
  nesting: conceptId("exponents_roots_properties", "power of a power versus exponent tower"),
  zeroNegative: conceptId("exponents_roots_properties", "zero and negative exponents"),
  fractional: conceptId("exponents_roots_properties", "fractional exponents and roots"),
  commonBase: conceptId("exponents_roots_properties", "common-base exponential equations"),
  repeated: conceptId("exponents_roots_properties", "repeated equal power terms"),
  evenSign: conceptId("exponents_roots_properties", "even-power absolute-value recovery"),
  preserveZero: conceptId("exponents_roots_properties", "preserve zero solutions"),
  radicals: conceptId("exponents_roots_properties", "radical simplification and domain"),
  powerSign: conceptId("exponents_roots_properties", "sign of integer powers"),
  ordering: conceptId("exponents_roots_properties", "power ordering by number-line region"),
  equalsOne: conceptId("exponents_roots_properties", "complete cases for a power equal to one"),
  hiddenQuadratic: conceptId("exponents_roots_properties", "hidden quadratic exponential equations"),
  fluency: conceptId("exponents_roots_properties", "power-value representation fluency"),
} as const;

const A = {
  dictionary: conceptId("algebraic_translation", "phrase-to-operator dictionary"),
  order: conceptId("algebraic_translation", "less-than and difference order"),
  inequalityWords: conceptId("algebraic_translation", "inequality phrase strictness"),
  integerEndpoints: conceptId("algebraic_translation", "integer endpoint translation"),
  linkedOneVariable: conceptId("algebraic_translation", "linked quantities in one variable"),
  sameTotal: conceptId("algebraic_translation", "fixed total as two expressions"),
  fixedPool: conceptId("algebraic_translation", "fixed-pool split model"),
  ages: conceptId("algebraic_translation", "age-shift model"),
  sumDifference: conceptId("algebraic_translation", "sum-and-difference recovery"),
  pairwise: conceptId("algebraic_translation", "pairwise-sum recovery"),
  consistency: conceptId("algebraic_translation", "linear-system consistency check"),
  digits: conceptId("algebraic_translation", "place-value digit model"),
  integerConstraints: conceptId("algebraic_translation", "positive-integer constraint enumeration"),
} as const;

const P = {
  basic: conceptId("probability", "equiprobable favorable-over-total"),
  complement: conceptId("probability", "complement event construction"),
  atLeastOne: conceptId("probability", "at-least-one via complement"),
  independent: conceptId("probability", "independent intersection multiplication"),
  withoutReplacement: conceptId("probability", "conditional probability without replacement"),
  combinations: conceptId("probability", "combination probability"),
  union: conceptId("probability", "union inclusion-exclusion"),
  exactlyOne: conceptId("probability", "exactly one of two independent events"),
  restricted: conceptId("probability", "conditional restricted sample spaces"),
  parity: conceptId("probability", "parity event modeling"),
  circular: conceptId("probability", "circular adjacency symmetry"),
  exactK: conceptId("probability", "exact-k successes in repeated trials"),
  occupancy: conceptId("probability", "occupancy collision probability"),
  fixedPoints: conceptId("probability", "matching and fixed-point probability"),
  inverseComposition: conceptId("probability", "inverse without-replacement composition inference"),
  stoppingTime: conceptId("probability", "finite stopping-time probability"),
} as const;

export const PILOT_CONCEPT_IDS = { exponents: E, algebraicTranslation: A, probability: P } as const;

const misconception = (chapter: Subtopic, name: string) =>
  entityId("misconception", chapter, name);
const archetype = (chapter: Subtopic, name: string) => entityId("archetype", chapter, name);
const surface = (chapter: Subtopic, name: string) => entityId("surface", chapter, name);

type PilotSpec = {
  id: string;
  chapter: (typeof PILOT_SUBTOPICS)[number];
  title: string;
  objective: string;
  sourceIdeas: readonly string[];
  prerequisites?: readonly string[];
  boundaries: readonly string[];
  edgeCases: readonly string[];
  confusables?: readonly string[];
  procedure: readonly string[];
  cues: readonly string[];
  unsafeWhen: readonly string[];
  misconceptions?: readonly string[];
  archetypes?: readonly string[];
  difficulty?: readonly [number, number];
  bankEvidence?: string;
};

function pilot(spec: PilotSpec): ConceptRecord {
  const officialDomains = spec.chapter === "algebraic_translation"
    ? (["algebra"] as const)
    : (["arithmetic", "algebra"] as const);
  const archetypeIds = spec.archetypes ?? [archetype(spec.chapter, spec.title)];
  return {
    id: spec.id,
    kind: "assessable_leaf",
    applicableSections: ["quant", "data_insights_ds_bridge"],
    officialDomains,
    parentSubtopic: spec.chapter,
    title: spec.title,
    objective: spec.objective,
    prerequisiteConceptIds: spec.prerequisites ?? [],
    canonicalOwner: spec.id,
    boundaries: spec.boundaries,
    edgeCases: spec.edgeCases,
    confusableConceptIds: spec.confusables ?? [],
    methods: [
      {
        id: entityId("method", spec.chapter, spec.title),
        title: spec.title,
        procedure: spec.procedure,
        decisionCues: spec.cues,
        unsafeWhen: spec.unsafeWhen,
      },
    ],
    misconceptionIds: spec.misconceptions ?? [],
    archetypeIds,
    surfaceFormIds: archetypeIds.map((id) => id.replace(/^archetype\./, "surface.")),
    intendedDifficulty: spec.difficulty ?? [2, 5],
    lessonStatus: spec.sourceIdeas.length > 0 ? "source_only" : "none",
    assessmentStatus: "insufficient",
    productionReady: false,
    provenance: spec.sourceIdeas.length > 0
      ? [
          {
            kind: "q86_lesson",
            path: `content/lessons/${spec.chapter}.md`,
            section: "The core ideas",
            anchor: spec.sourceIdeas.join("; "),
            checkedOn: "2026-07-21",
          },
        ]
      : [
          {
            kind: "q86_bank",
            path: "scripts/seed-bank.json",
            section: "questions",
            anchor: spec.bankEvidence,
            checkedOn: "2026-07-21",
          },
        ],
    contentVersion: "3.0.0-draft.1",
    sourceCoreIdeaIds: spec.sourceIdeas.map((anchor) => sourceIdeaId(spec.chapter, anchor)),
  };
}

export const PILOT_CONCEPTS: readonly ConceptRecord[] = [
  pilot({
    id: E.combine,
    chapter: "exponents_roots_properties",
    title: "Combine powers with the same base",
    objective: "Given products or quotients of powers with one nonzero base, combine them by adding or subtracting exponents and state the domain restriction.",
    sourceIdeas: ["Product rule", "Quotient rule"],
    boundaries: ["Applies only when the bases match.", "A quotient requires a nonzero base."],
    edgeCases: ["A resulting exponent may be zero or negative."],
    confusables: [E.repeated, E.nesting],
    procedure: ["Rewrite factors with one base.", "Add exponents for multiplication and subtract for division.", "Apply zero or negative-exponent meaning only after combining."],
    cues: ["same-base product", "same-base quotient"],
    unsafeWhen: ["The expression is a sum rather than a product.", "The bases have not actually been made equal."],
    difficulty: [1, 3],
  }),
  pilot({
    id: E.nesting,
    chapter: "exponents_roots_properties",
    title: "Distinguish a power of a power from an exponent tower",
    objective: "Evaluate nested powers by reading parentheses and applying exponent precedence without turning a tower into a product of exponents.",
    sourceIdeas: ["Power rule"],
    prerequisites: [E.combine],
    boundaries: ["Multiplication of exponents applies to an explicitly parenthesized power raised to a power."],
    edgeCases: ["Exponent towers are evaluated from the top down."],
    confusables: [E.combine],
    procedure: ["Mark the base controlled by each exponent.", "If a completed power is parenthesized, multiply exponents.", "If an exponent itself is powered, evaluate that exponent first."],
    cues: ["nested parentheses", "stacked exponents"],
    unsafeWhen: ["Parentheses do not enclose the first power."],
    misconceptions: [misconception("exponents_roots_properties", "tower confusion")],
    difficulty: [2, 4],
  }),
  pilot({
    id: E.zeroNegative,
    chapter: "exponents_roots_properties",
    title: "Interpret zero and negative exponents",
    objective: "Rewrite zero and negative integer exponents as valid reciprocal expressions while enforcing nonzero-base restrictions.",
    sourceIdeas: ["Zero and negative exponents"],
    prerequisites: [E.combine],
    boundaries: ["The base must be nonzero for zero or negative exponents."],
    edgeCases: ["A negative exponent on a fraction reciprocates the entire fraction."],
    confusables: [E.powerSign],
    procedure: ["Check that the base is nonzero.", "Replace a zero exponent with one.", "For a negative exponent, reciprocate the base and make the exponent positive."],
    cues: ["negative exponent", "fraction raised to a negative power"],
    unsafeWhen: ["The base might be zero."],
    difficulty: [1, 3],
  }),
  pilot({
    id: E.fractional,
    chapter: "exponents_roots_properties",
    title: "Translate between fractional exponents and roots",
    objective: "Rewrite a rational exponent as a root and power, choose a computationally efficient order, and respect the real-number domain.",
    sourceIdeas: ["Fractional exponents"],
    prerequisites: [E.nesting],
    boundaries: ["For real values, an even root requires a nonnegative radicand."],
    edgeCases: ["Reducing the exponent fraction can change which domain restriction is visible."],
    confusables: [E.radicals],
    procedure: ["Reduce the rational exponent.", "Use the denominator as the root and numerator as the power.", "Take the root first when it keeps values small."],
    cues: ["exponent written as a fraction", "root rewritten as a power"],
    unsafeWhen: ["A real even root of a negative number is implied."],
    difficulty: [2, 4],
  }),
  pilot({
    id: E.commonBase,
    chapter: "exponents_roots_properties",
    title: "Solve exponential equations with a common base",
    objective: "Convert compatible bases to one valid base and equate exponents only when the base makes that inference one-to-one.",
    sourceIdeas: ["Common-base conversion"],
    prerequisites: [E.combine, E.nesting],
    boundaries: ["Equating exponents requires a positive base other than one."],
    edgeCases: ["Bases zero, one, or negative require separate case analysis."],
    confusables: [E.fluency, E.equalsOne],
    procedure: ["Prime-factor or otherwise rewrite every base.", "Simplify with exponent laws.", "Verify the common base is positive and not one.", "Equate and solve the exponents."],
    cues: ["related bases", "exponential equation"],
    unsafeWhen: ["The base is unknown and could be zero, one, or negative."],
    misconceptions: [misconception("exponents_roots_properties", "equating exponents too early")],
    archetypes: [
      archetype("exponents_roots_properties", "mixed related bases"),
      archetype("exponents_roots_properties", "exponential growth comparison"),
    ],
  }),
  pilot({
    id: E.repeated,
    chapter: "exponents_roots_properties",
    title: "Factor repeated equal power terms",
    objective: "Collapse repeated addition of an identical power by factoring the common term rather than adding exponents.",
    sourceIdeas: ["Repeated addition of the same power"],
    prerequisites: [E.combine],
    boundaries: ["Every added term must be identical before factoring by count."],
    edgeCases: ["When the copy count equals a compatible base, the coefficient can become another power."],
    confusables: [E.combine],
    procedure: ["Confirm the terms are identical.", "Count the copies.", "Factor as count times the common power.", "Convert the coefficient to the common base when useful."],
    cues: ["the same power appears across plus signs"],
    unsafeWhen: ["The terms have different exponents or coefficients."],
    misconceptions: [misconception("exponents_roots_properties", "adding exponents across a plus sign")],
    archetypes: [archetype("exponents_roots_properties", "same power repeated")],
    difficulty: [2, 4],
  }),
  pilot({
    id: E.evenSign,
    chapter: "exponents_roots_properties",
    title: "Recover magnitude after an even power",
    objective: "Interpret a principal square root of a square as absolute value and preserve both legal signs when solving.",
    sourceIdeas: ["Even powers erase sign"],
    boundaries: ["The radical symbol denotes the nonnegative principal root."],
    edgeCases: ["Zero is its own positive and negative candidate."],
    confusables: [E.powerSign, E.preserveZero],
    procedure: ["Replace the square-root-of-square expression with absolute value.", "Solve the magnitude statement.", "Test positive and negative candidates in the original target."],
    cues: ["square root of a square", "even power in Data Sufficiency"],
    unsafeWhen: ["Dropping absolute-value bars would erase a valid sign."],
    misconceptions: [misconception("exponents_roots_properties", "square root of x squared equals x")],
    archetypes: [archetype("exponents_roots_properties", "even power sign recovery")],
  }),
  pilot({
    id: E.preserveZero,
    chapter: "exponents_roots_properties",
    title: "Preserve zero solutions while rearranging equations",
    objective: "Solve equations containing a variable factor without dividing by a quantity that could be zero.",
    sourceIdeas: ["Never divide by a variable that might be zero"],
    prerequisites: [conceptId("quadratics_factoring", "Zero-product property")],
    boundaries: ["Division is safe only after the divisor is known to be nonzero."],
    edgeCases: ["A stem may explicitly exclude zero, making division valid."],
    confusables: [E.evenSign],
    procedure: ["Move all terms to one side.", "Factor completely.", "Apply the zero-product property.", "Check every candidate in the original equation."],
    cues: ["the same variable factor appears on both sides"],
    unsafeWhen: ["Cancelling would require assuming the variable is nonzero."],
    misconceptions: [misconception("exponents_roots_properties", "dividing by the variable")],
    difficulty: [2, 4],
  }),
  pilot({
    id: E.radicals,
    chapter: "exponents_roots_properties",
    title: "Simplify radicals without splitting sums",
    objective: "Extract perfect-power factors from valid real radicals and distinguish multiplication rules from invalid addition rules.",
    sourceIdeas: ["Radical arithmetic"],
    prerequisites: [E.fractional],
    boundaries: ["Product splitting over real square roots assumes nonnegative factors."],
    edgeCases: ["Roots do not distribute over addition or subtraction."],
    confusables: [E.fractional],
    procedure: ["Factor the radicand into a largest perfect square and remainder.", "Extract the square root of that factor.", "Combine only like radical terms."],
    cues: ["sum or difference of radicals", "large composite radicand"],
    unsafeWhen: ["A proposed step splits a root across a plus sign."],
    difficulty: [1, 4],
  }),
  pilot({
    id: E.powerSign,
    chapter: "exponents_roots_properties",
    title: "Determine the sign of an integer power",
    objective: "Determine a power's sign from the base sign and integer-exponent parity, including the role of zero.",
    sourceIdeas: ["Sign of a power"],
    prerequisites: [conceptId("parity_signs", "Powers preserve parity")],
    boundaries: ["The even/odd rule stated here is for integer exponents."],
    edgeCases: ["A zero base gives zero for positive exponents, neither positive nor negative."],
    confusables: [E.evenSign, E.zeroNegative],
    procedure: ["Classify the base as positive, negative, or zero.", "If negative, classify the integer exponent as even or odd.", "Apply the resulting sign."],
    cues: ["negative base", "is the power positive"],
    unsafeWhen: ["The exponent is not known to be an integer."],
    difficulty: [1, 4],
  }),
  pilot({
    id: E.ordering,
    chapter: "exponents_roots_properties",
    title: "Order powers by number-line region",
    objective: "Compare a positive value, its square, and its square root by first locating the value relative to zero and one.",
    sourceIdeas: ["Ordering flips between 0 and 1"],
    prerequisites: [E.fractional],
    boundaries: ["The square-root comparison requires a nonnegative real input."],
    edgeCases: ["At zero and one, some expressions are equal; negative values require separate domain checks."],
    confusables: [conceptId("inequalities", "Squares are never negative")],
    procedure: ["Split the domain at zero and one.", "Select the legal region from the givens.", "Use a benchmark or monotonicity to order the expressions."],
    cues: ["compare x, x squared, and square root x"],
    unsafeWhen: ["The sign or domain of the variable has not been established."],
    misconceptions: [misconception("exponents_roots_properties", "squaring makes bigger")],
    archetypes: [archetype("exponents_roots_properties", "power ordering by region")],
  }),
  pilot({
    id: E.equalsOne,
    chapter: "exponents_roots_properties",
    title: "Enumerate every case that makes a power equal one",
    objective: "For real-base integer-exponent equations of the form w^k = 1, enumerate base-one, exponent-zero, and negative-one/even-exponent cases before solving constraints.",
    sourceIdeas: ["When does w k = 1"],
    prerequisites: [E.zeroNegative, E.powerSign],
    boundaries: ["The listed cases assume the exponent and real-domain conditions in the problem."],
    edgeCases: ["Zero to the zero power is not licensed by the zero-exponent rule."],
    confusables: [E.commonBase],
    procedure: ["Write the three case families.", "Intersect each family with the stem's domain.", "Solve and verify surviving candidates."],
    cues: ["variable base raised to a variable expression equals one"],
    unsafeWhen: ["Treating the equation as though only base one were possible."],
    difficulty: [3, 5],
  }),
  pilot({
    id: E.hiddenQuadratic,
    chapter: "exponents_roots_properties",
    title: "Solve a hidden quadratic in an exponential expression",
    objective: "Substitute y = a^x in equations containing a^(2x) and a^x, enforce y's range, and recover every valid x.",
    sourceIdeas: ["Hidden quadratics"],
    prerequisites: [E.commonBase, conceptId("quadratics_factoring", "Zero-product property")],
    boundaries: ["The substitution requires a^(2x) to equal (a^x)^2."],
    edgeCases: ["For a positive base, nonpositive quadratic roots are impossible values of a^x."],
    confusables: [E.nesting],
    procedure: ["Choose y = a^x and state y's range.", "Rewrite as a quadratic in y.", "Solve and discard range violations.", "Solve each surviving exponential equation for x."],
    cues: ["both a to the 2x and a to the x appear"],
    unsafeWhen: ["The base or exponent structure does not support the square substitution."],
    misconceptions: [misconception("exponents_roots_properties", "keeping impossible substitution roots")],
    archetypes: [archetype("exponents_roots_properties", "hidden exponential quadratic")],
    difficulty: [4, 5],
  }),
  pilot({
    id: E.fluency,
    chapter: "exponents_roots_properties",
    title: "Recognize equivalent power representations",
    objective: "Recognize benchmark powers and enumerate equivalent integer base-exponent representations without computing large values directly.",
    sourceIdeas: ["Memorized ladder"],
    prerequisites: [E.nesting],
    boundaries: ["Fluency supports reasoning; it does not replace proof when the base or exponent domain is open."],
    edgeCases: ["The same value can have several composite-base representations."],
    confusables: [E.commonBase],
    procedure: ["Prime-factor the target or recall its benchmark power.", "Factor the prime exponent into valid base/exponent pairs.", "Apply all stated integer and ordering constraints."],
    cues: ["power-rich constants such as 4096 or 729"],
    unsafeWhen: ["Stopping after the first representation in a sufficiency problem."],
    misconceptions: [misconception("exponents_roots_properties", "assuming one power representation")],
    archetypes: [archetype("exponents_roots_properties", "power-rich constant representations")],
    difficulty: [2, 5],
  }),

  pilot({
    id: A.dictionary,
    chapter: "algebraic_translation",
    title: "Translate noun phrases into algebraic objects",
    objective: "Translate sum, difference, product, quotient, and equality phrases into a parenthesized algebraic statement without changing their roles.",
    sourceIdeas: ["The dictionary"],
    boundaries: ["Each complete noun phrase should become one algebraic object before operations are combined."],
    edgeCases: ["Words can nest, requiring explicit parentheses."],
    confusables: [A.order, A.inequalityWords],
    procedure: ["Underline each noun phrase.", "Translate the innermost objects.", "Add parentheses before attaching multipliers or comparisons.", "Read the finished equation back in words."],
    cues: ["sum of", "difference of", "times the quantity"],
    unsafeWhen: ["Word order or grouping is being handled mentally without parentheses."],
    misconceptions: [misconception("algebraic_translation", "trusting the translated equation over the words")],
    difficulty: [1, 3],
  }),
  pilot({
    id: A.order,
    chapter: "algebraic_translation",
    title: "Preserve order in less-than and difference phrases",
    objective: "Translate k less than m and the difference of a and b with the subtrahend in the correct position.",
    sourceIdeas: ["Less than reverses"],
    prerequisites: [A.dictionary],
    boundaries: ["The reversal applies to the English construction 'k less than m,' not to every use of the word less."],
    edgeCases: ["A nested phrase may require reversing an entire expression, not one term."],
    confusables: [A.inequalityWords],
    procedure: ["Identify the reference quantity after 'than' or 'of'.", "Write that quantity first.", "Subtract the named amount and check by a concrete example."],
    cues: ["less than", "difference of"],
    unsafeWhen: ["The phrase is actually a comparison such as 'is less than'."],
    misconceptions: [
      misconception("algebraic_translation", "reversed subtraction"),
      misconception("algebraic_translation", "difference order"),
    ],
    difficulty: [1, 4],
  }),
  pilot({
    id: A.inequalityWords,
    chapter: "algebraic_translation",
    title: "Translate strict and inclusive inequality language",
    objective: "Map comparison phrases to the correct strict or inclusive inequality, including absolute-distance language.",
    sourceIdeas: ["Inequality words"],
    prerequisites: [A.dictionary],
    boundaries: ["At least and at most include the boundary; more/fewer than do not."],
    edgeCases: ["Differs from a value by more than d becomes an absolute-value inequality."],
    confusables: [A.order, A.integerEndpoints],
    procedure: ["Name the compared quantities.", "Choose strict or inclusive from the exact phrase.", "Use absolute value for unsigned distance.", "Test the boundary sentence."],
    cues: ["at least", "at most", "differs by"],
    unsafeWhen: ["The reference quantity or included boundary has not been identified."],
    misconceptions: [misconception("algebraic_translation", "strictness slip")],
    archetypes: [archetype("algebraic_translation", "verbal inequality")],
    difficulty: [1, 4],
  }),
  pilot({
    id: A.integerEndpoints,
    chapter: "algebraic_translation",
    title: "Convert real bounds to integer endpoints",
    objective: "Given a strict or inclusive real bound, identify the smallest or greatest permitted integer without rounding in the wrong direction.",
    sourceIdeas: ["Integer endpoints"],
    prerequisites: [A.inequalityWords],
    boundaries: ["The requested value must be constrained to integers."],
    edgeCases: ["An integer boundary behaves differently under strict and inclusive signs."],
    confusables: [A.inequalityWords],
    procedure: ["Solve the inequality over the reals.", "Draw or imagine the boundary and inclusion mark.", "Step to the nearest allowed integer in the requested direction."],
    cues: ["smallest integer", "greatest integer"],
    unsafeWhen: ["Ordinary nearest-integer rounding is substituted for set membership."],
    misconceptions: [misconception("algebraic_translation", "wrong-direction rounding")],
    difficulty: [2, 4],
  }),
  pilot({
    id: A.linkedOneVariable,
    chapter: "algebraic_translation",
    title: "Model linked quantities with one variable",
    objective: "Represent quantities joined by a fixed multiplicative or additive relation using one independent variable and answer the requested quantity.",
    sourceIdeas: ["One variable when quantities are linked"],
    prerequisites: [A.dictionary],
    boundaries: ["The linking statement must determine one quantity from the other."],
    edgeCases: ["The solved variable may not be the quantity the question asks for."],
    confusables: [A.sumDifference],
    procedure: ["Choose the simpler quantity as the variable.", "Express every linked quantity from it.", "Use the total or remaining condition.", "Convert back to the asked-for quantity."],
    cues: ["twice as many", "more than another quantity"],
    unsafeWhen: ["The relation is not one-to-one or a necessary independent condition is absent."],
    misconceptions: [misconception("algebraic_translation", "answering the wrong quantity")],
  }),
  pilot({
    id: A.sameTotal,
    chapter: "algebraic_translation",
    title: "Write a fixed total as two expressions",
    objective: "Translate leftover and shortfall statements into two expressions for the same fixed total and solve their equality.",
    sourceIdeas: ["Same quantity, two expressions"],
    prerequisites: [A.dictionary],
    boundaries: ["Leftover is added to spending; shortfall is subtracted from required cost when expressing current money."],
    edgeCases: ["Prices or counts may be constrained to whole numbers."],
    confusables: [A.fixedPool],
    procedure: ["Name the fixed total.", "Write purchase cost plus leftover.", "Write desired cost minus shortfall.", "Set the two expressions equal and verify both stories."],
    cues: ["has money left", "would need more"],
    unsafeWhen: ["Leftover and shortfall signs are assigned from keywords without checking the story."],
    archetypes: [archetype("algebraic_translation", "leftover and shortfall")],
    difficulty: [2, 4],
  }),
  pilot({
    id: A.fixedPool,
    chapter: "algebraic_translation",
    title: "Model a fixed pool split among different group sizes",
    objective: "Represent per-person shares of an unchanged total under two group sizes and solve the resulting share-difference equation.",
    sourceIdeas: ["Fixed pool split"],
    prerequisites: [A.dictionary],
    boundaries: ["The total pool must remain unchanged between scenarios."],
    edgeCases: ["A smaller group receives the larger per-person share when the pool is positive."],
    confusables: [A.sameTotal],
    procedure: ["Name the fixed total T.", "Write each per-person share as T divided by group size.", "Translate the share difference with its direction.", "Solve and sanity-check monotonicity."],
    cues: ["each of m receives d more than each of n"],
    unsafeWhen: ["The total changes between scenarios."],
    archetypes: [archetype("algebraic_translation", "fixed pool shares")],
    difficulty: [3, 4],
  }),
  pilot({
    id: A.ages,
    chapter: "algebraic_translation",
    title: "Shift every age across time",
    objective: "Build present and future age equations by applying the same elapsed-time shift to every person's age.",
    sourceIdeas: ["Age shift"],
    prerequisites: [A.linkedOneVariable],
    boundaries: ["Elapsed time adds equally to all ages, not to age ratios."],
    edgeCases: ["Past-time language subtracts the shift from every age."],
    confusables: [A.linkedOneVariable],
    procedure: ["Create present-age expressions.", "Add or subtract the time shift to every person.", "Apply the future or past relation only after shifting.", "Check both time snapshots."],
    cues: ["in t years", "t years ago"],
    unsafeWhen: ["Only one person's age has been shifted."],
    misconceptions: [misconception("algebraic_translation", "aging one person")],
    archetypes: [archetype("algebraic_translation", "age timeline")],
  }),
  pilot({
    id: A.sumDifference,
    chapter: "algebraic_translation",
    title: "Recover two values from their sum and difference",
    objective: "Recover the larger and smaller values from a stated sum and signed difference using half-sum and half-difference.",
    sourceIdeas: ["Sum and difference"],
    prerequisites: [A.order],
    boundaries: ["The sign and order of the stated difference identify which value is larger."],
    edgeCases: ["Integer requirements imply sum and difference must have compatible parity."],
    confusables: [A.pairwise],
    procedure: ["Write S and the signed D.", "Compute (S + D)/2 for the first value.", "Compute (S - D)/2 for the second.", "Verify sum and difference."],
    cues: ["sum and difference"],
    unsafeWhen: ["The word difference is unsigned and larger-versus-smaller has not been established."],
    archetypes: [archetype("algebraic_translation", "sum and difference")],
    difficulty: [2, 4],
  }),
  pilot({
    id: A.pairwise,
    chapter: "algebraic_translation",
    title: "Recover variables from three pairwise sums",
    objective: "Use three pairwise sums to recover the total and each individual value without solving a full system.",
    sourceIdeas: ["Pairwise sums"],
    prerequisites: [A.sumDifference],
    boundaries: ["All three pair sums must refer to the same three quantities."],
    edgeCases: ["Their total is twice the three-variable total."],
    confusables: [A.sumDifference],
    procedure: ["Add the three pairwise sums.", "Halve to get the total of all variables.", "Subtract the pair sum that omits the desired variable."],
    cues: ["a plus b, a plus c, b plus c"],
    unsafeWhen: ["A listed equation is not a pair sum or a variable has a different coefficient."],
    archetypes: [archetype("algebraic_translation", "three pairwise sums")],
    difficulty: [3, 4],
  }),
  pilot({
    id: A.consistency,
    chapter: "algebraic_translation",
    title: "Test whether an additional linear equation is consistent",
    objective: "Solve two independent linear equations and determine the parameter that makes a third equation true at their unique intersection.",
    sourceIdeas: ["Consistency of a third equation"],
    prerequisites: [conceptId("linear_systems", "Unique solution test")],
    boundaries: ["The first two equations must be independent to identify one point."],
    edgeCases: ["Dependent or inconsistent first equations require a separate structural analysis."],
    confusables: [conceptId("linear_systems", "Parallel vs identical")],
    procedure: ["Verify the first two equations are independent.", "Solve their intersection.", "Substitute it into the parameterized equation.", "Solve for the parameter and recheck."],
    cues: ["third equation holds automatically", "system is consistent for what parameter"],
    unsafeWhen: ["The first two equations do not determine a unique point."],
    archetypes: [archetype("algebraic_translation", "parameterized third equation")],
    difficulty: [3, 5],
  }),
  pilot({
    id: A.digits,
    chapter: "algebraic_translation",
    title: "Translate digits with place-value coefficients",
    objective: "Represent a multi-digit number and its reversal using place-value coefficients, then translate digit constraints algebraically.",
    sourceIdeas: ["Digits are coefficients"],
    prerequisites: [A.dictionary],
    boundaries: ["A leading digit cannot be zero; each digit is an integer from zero through nine."],
    edgeCases: ["Reversing a three-digit number changes it by 99 times the last-minus-first digit."],
    confusables: [conceptId("remainders_units_digits", "Units digit is a remainder")],
    procedure: ["Assign one variable to each digit.", "Build the number with powers-of-ten coefficients.", "Build the reversed number.", "Apply digit bounds and solve."],
    cues: ["digits sum", "number reversed"],
    unsafeWhen: ["Digit bounds or the nonzero leading digit are omitted."],
    archetypes: [archetype("algebraic_translation", "reversed digits")],
    difficulty: [3, 5],
  }),
  pilot({
    id: A.integerConstraints,
    chapter: "algebraic_translation",
    title: "Use positivity and integrality to collapse an underdetermined equation",
    objective: "Determine whether a linear equation in two positive integers has zero, one, or several feasible solutions by bounding and modular enumeration.",
    sourceIdeas: ["Integer constraints collapse equations"],
    prerequisites: [A.dictionary, conceptId("divisibility_gcf_lcm", "Divisibility")],
    boundaries: ["The technique relies on explicit integer and sign constraints."],
    edgeCases: ["One equation in two variables can be sufficient when only one lattice point is feasible."],
    confusables: [conceptId("data_sufficiency_discipline", "Equation counting is a heuristic with famous failures")],
    procedure: ["Record all integer and positivity constraints.", "Bound one variable.", "Use congruence or divisibility to prune candidates.", "Enumerate every feasible pair before judging uniqueness."],
    cues: ["whole-number counts", "one equation in two integer unknowns"],
    unsafeWhen: ["Assuming uniqueness after finding the first feasible pair."],
    misconceptions: [misconception("algebraic_translation", "auto-insufficient equation counting")],
    archetypes: [archetype("algebraic_translation", "integer value equation")],
    difficulty: [3, 5],
  }),

  pilot({
    id: P.basic,
    chapter: "probability",
    title: "Compute probability in an equiprobable sample space",
    objective: "Define an equiprobable sample space and compute favorable outcomes divided by total outcomes without relying on unsupported symmetry.",
    sourceIdeas: ["Basic definition"],
    boundaries: ["Favorable-over-total applies directly only when elementary outcomes are equally likely."],
    edgeCases: ["Ties or fixed points can break an apparent half-and-half symmetry."],
    confusables: [P.restricted, P.combinations],
    procedure: ["Define one elementary outcome.", "Verify equal likelihood.", "Count total and favorable outcomes in the same representation.", "Check the result is between zero and one."],
    cues: ["selected at random", "fair die or coin"],
    unsafeWhen: ["The outcome categories have unequal sizes or probabilities."],
    misconceptions: [misconception("probability", "false fifty-fifty symmetry")],
    difficulty: [1, 4],
  }),
  pilot({
    id: P.complement,
    chapter: "probability",
    title: "Construct and compute the exact complement event",
    objective: "State the logical complement of an event and use one minus its probability without dropping cases.",
    sourceIdeas: ["Complement rule"],
    prerequisites: [P.basic],
    boundaries: ["The event and its complement must be disjoint and exhaustive."],
    edgeCases: ["The complement of at least k is at most k minus one, not always none."],
    confusables: [P.atLeastOne],
    procedure: ["Restate the target as a set of outcomes.", "Negate it exactly.", "Compute the complement probability.", "Subtract from one."],
    cues: ["the opposite side has fewer cases"],
    unsafeWhen: ["The proposed opposite event leaves intermediate cases uncounted."],
    misconceptions: [misconception("probability", "wrong complement")],
    difficulty: [2, 5],
  }),
  pilot({
    id: P.atLeastOne,
    chapter: "probability",
    title: "Use the complement for at least one event",
    objective: "Compute an at-least-one probability as one minus the all-none event, including independent and without-replacement settings.",
    sourceIdeas: ["At least one"],
    prerequisites: [P.complement],
    boundaries: ["The shortcut is exact for at least one; at least two has a different complement."],
    edgeCases: ["The all-none factors may be independent or conditional, depending on replacement."],
    confusables: [P.complement, P.withoutReplacement],
    procedure: ["Translate at least one to the complement none.", "Choose independent or conditional factors for all failures.", "Multiply those factors.", "Subtract from one."],
    cues: ["at least one", "none is a single clean path"],
    unsafeWhen: ["The target threshold exceeds one or dependence is ignored."],
    archetypes: [archetype("probability", "at least one complement")],
    difficulty: [2, 5],
  }),
  pilot({
    id: P.independent,
    chapter: "probability",
    title: "Multiply independent event probabilities",
    objective: "Compute the intersection of independent events by multiplying their probabilities and distinguish that operation from adding alternatives.",
    sourceIdeas: ["Independent events multiply"],
    prerequisites: [P.basic],
    boundaries: ["Multiplication of marginal probabilities requires independence."],
    edgeCases: ["Repeated Bernoulli trials remain independent only when the process says so."],
    confusables: [P.withoutReplacement, P.union],
    procedure: ["Identify the required joint event.", "Verify independence from the process or wording.", "Multiply the marginal probabilities.", "Check the joint probability does not exceed either marginal."],
    cues: ["independently", "both events"],
    unsafeWhen: ["One outcome changes the probability of the next."],
    misconceptions: [misconception("probability", "adding when multiplication is required")],
    difficulty: [1, 4],
  }),
  pilot({
    id: P.withoutReplacement,
    chapter: "probability",
    title: "Multiply conditional probabilities without replacement",
    objective: "Compute a specified sequential draw event by updating favorable and total counts after each draw.",
    sourceIdeas: ["Without replacement shrink as you go"],
    prerequisites: [P.basic],
    boundaries: ["Every draw changes the remaining pool when the object is not replaced."],
    edgeCases: ["The numerator changes only if the previous draw removed an object of the relevant type."],
    confusables: [P.independent, P.combinations],
    procedure: ["Write the exact required sequence.", "For each draw, update the remaining total and favorable count.", "Multiply the conditional fractions.", "Cross-check with combinations when order is irrelevant."],
    cues: ["without replacement", "one after another", "first special item occurs at k"],
    unsafeWhen: ["Reusing the original denominator after a draw."],
    misconceptions: [misconception("probability", "frozen denominator")],
    archetypes: [
      archetype("probability", "without-replacement sequence"),
      archetype("probability", "first special item position"),
    ],
    difficulty: [2, 5],
  }),
  pilot({
    id: P.combinations,
    chapter: "probability",
    title: "Compute unordered-selection probability with combinations",
    objective: "Count favorable and total unordered selections with combinations, including quota cases, using the same sample-space representation.",
    sourceIdeas: ["Combination form", "Stay consistent"],
    prerequisites: [P.basic, conceptId("combinatorics", "Combinations order irrelevant")],
    boundaries: ["The selected group's order must be irrelevant."],
    edgeCases: ["At-least quotas split into disjoint exact-count cases."],
    confusables: [P.withoutReplacement],
    procedure: ["Confirm order is irrelevant.", "Count total groups with one combination.", "Split favorable groups into disjoint quota cases.", "Add favorable counts and divide by total."],
    cues: ["committee", "team", "selection of r"],
    unsafeWhen: ["The outcome records an order or role assignment."],
    misconceptions: [misconception("probability", "ordered-unordered mixing")],
    archetypes: [archetype("probability", "committee quota")],
    difficulty: [2, 5],
  }),
  pilot({
    id: P.union,
    chapter: "probability",
    title: "Compute event unions with inclusion-exclusion",
    objective: "Compute P(A or B) by adding event probabilities and subtracting their overlap exactly once.",
    sourceIdeas: ["Or means inclusion-exclusion"],
    prerequisites: [P.basic],
    boundaries: ["Simple addition is valid only when the events are mutually exclusive."],
    edgeCases: ["An explicit impossibility of overlap reduces the formula to addition."],
    confusables: [P.independent, P.exactlyOne],
    procedure: ["Define A, B, and their intersection.", "Count or compute each probability.", "Add A and B, then subtract the intersection.", "Check that overlap is not negative or larger than either event."],
    cues: ["or", "multiple of a or b"],
    unsafeWhen: ["The overlap has not been considered."],
    misconceptions: [misconception("probability", "forgetting the overlap")],
    archetypes: [archetype("probability", "integer multiple union")],
    difficulty: [2, 5],
  }),
  pilot({
    id: P.exactlyOne,
    chapter: "probability",
    title: "Compute exactly one of two independent events",
    objective: "Compute exactly one success across two independent events by adding the two disjoint success-failure orders.",
    sourceIdeas: ["Exactly one of two independent events"],
    prerequisites: [P.independent, P.union],
    boundaries: ["The formula p(1-q) + (1-p)q assumes independence."],
    edgeCases: ["The event excludes both-success and both-failure."],
    confusables: [P.union],
    procedure: ["Write success-failure and failure-success as separate paths.", "Multiply within each independent path.", "Add the disjoint path probabilities."],
    cues: ["exactly one of two"],
    unsafeWhen: ["The two events are dependent or exactly one is confused with at least one."],
    archetypes: [archetype("probability", "exactly one independent event")],
    difficulty: [2, 4],
  }),
  pilot({
    id: P.restricted,
    chapter: "probability",
    title: "Redefine the sample space after a condition",
    objective: "When selection is explicitly restricted to a subgroup, use that subgroup as the denominator and count favorable members within it.",
    sourceIdeas: ["Restricted sample space"],
    prerequisites: [P.basic],
    boundaries: ["The condition must occur before or define the random selection."],
    edgeCases: ["Conditioning can change both numerator and denominator."],
    confusables: [P.basic],
    procedure: ["Underline the group from which selection occurs.", "Count that restricted group for the denominator.", "Count target members within the same group.", "Ignore members outside the conditioned pool."],
    cues: ["one of the remote employees", "given that the selected item is"],
    unsafeWhen: ["The whole-population denominator is retained after conditioning."],
    misconceptions: [misconception("probability", "whole-population denominator")],
    archetypes: [archetype("probability", "restricted subgroup selection")],
    difficulty: [2, 5],
  }),
  pilot({
    id: P.parity,
    chapter: "probability",
    title: "Model sum and product events with parity",
    objective: "Translate sum-even and product-even events into parity cases and compute them directly or by complement.",
    sourceIdeas: ["Parity rules"],
    prerequisites: [P.basic, conceptId("parity_signs", "Addition parity"), conceptId("parity_signs", "Multiplication parity")],
    boundaries: ["The parity distribution must be counted for the actual sample space."],
    edgeCases: ["Without replacement, the second parity probability is conditional."],
    confusables: [P.atLeastOne, P.withoutReplacement],
    procedure: ["Translate the target into same/different parity or at-least-one-even.", "Count even and odd possibilities.", "Choose direct cases or a complement.", "Use conditional fractions if sampling without replacement."],
    cues: ["sum even or odd", "product even or odd"],
    unsafeWhen: ["Assuming equal numbers of odd and even outcomes without counting."],
    archetypes: [archetype("probability", "parity event")],
    difficulty: [2, 5],
  }),
  pilot({
    id: P.circular,
    chapter: "probability",
    title: "Use symmetry for adjacency in a random circle",
    objective: "Fix one named object in a circular arrangement and compute adjacency probability from favorable remaining positions.",
    sourceIdeas: ["Symmetry fix one object"],
    prerequisites: [P.basic],
    boundaries: ["Seats or positions must be symmetric under rotation."],
    edgeCases: ["For n people, two of the n minus one remaining seats are adjacent when n is at least three."],
    confusables: [conceptId("combinatorics", "Glue method")],
    procedure: ["Fix the first named person to remove rotational symmetry.", "Count the remaining possible seats for the second.", "Count the two adjacent seats.", "Divide favorable by total."],
    cues: ["random circular seating", "two named people adjacent"],
    unsafeWhen: ["Seats have different labels or nonuniform assignment probabilities."],
    archetypes: [archetype("probability", "circular adjacency")],
    difficulty: [3, 5],
  }),
  pilot({
    id: P.exactK,
    chapter: "probability",
    title: "Count exactly k successes in repeated independent trials",
    objective: "Compute the probability of exactly k successes by multiplying one sequence probability by the number of distinct success positions.",
    sourceIdeas: [],
    bankEvidence: "seed questions 493 and 494",
    prerequisites: [P.independent, P.combinations],
    boundaries: ["Trials must be independent with a fixed success probability for the binomial shortcut."],
    edgeCases: ["More successes than failures can be counted directly or by symmetry only after tie cases are handled."],
    confusables: [P.atLeastOne, P.stoppingTime],
    procedure: ["Choose the k success positions.", "Multiply p^k by (1-p)^(n-k).", "Multiply by the combination count.", "Check that exactly—not at least—k was counted."],
    cues: ["exactly k of n independent attempts", "more heads than tails in a fixed number of flips"],
    unsafeWhen: ["Success probabilities change across trials or trials are dependent."],
    archetypes: [archetype("probability", "exact-k repeated trials")],
    difficulty: [2, 5],
  }),
  pilot({
    id: P.occupancy,
    chapter: "probability",
    title: "Compute occupancy and collision probabilities",
    objective: "Model independent assignments into equally likely categories and count collisions by complement or occupancy cases.",
    sourceIdeas: [],
    bankEvidence: "seed question 498",
    prerequisites: [P.independent, P.complement, P.combinations],
    boundaries: ["Each assignment must identify whether categories are labeled and whether choices are independent."],
    edgeCases: ["At least two share a category is often easiest as one minus all assignments distinct."],
    confusables: [P.atLeastOne, P.fixedPoints],
    procedure: ["Define one labeled assignment outcome.", "Count all assignments.", "Count the collision-free complement when simpler.", "Subtract from one or divide favorable by total."],
    cues: ["people independently choose among locations", "at least two choose the same"],
    unsafeWhen: ["Treating categories as unlabeled or ignoring capacity restrictions."],
    archetypes: [archetype("probability", "occupancy collision")],
    difficulty: [3, 5],
  }),
  pilot({
    id: P.fixedPoints,
    chapter: "probability",
    title: "Count matching and fixed-point events",
    objective: "Count permutations with an exact number of items in their matching positions using fixed choices and derangements of the remainder.",
    sourceIdeas: [],
    bankEvidence: "seed question 499",
    prerequisites: [P.basic, P.combinations],
    boundaries: ["Objects and destinations are distinct and assignments are one-to-one."],
    edgeCases: ["Exactly one fixed point is impossible for two remaining objects because a one-element mismatch cannot stand alone."],
    confusables: [P.occupancy, conceptId("combinatorics", "Permutations of n distinct objects")],
    procedure: ["Choose which positions are fixed.", "Count derangements of the remaining objects.", "Multiply and divide by all permutations.", "Check small remainder cases explicitly."],
    cues: ["letters into addressed envelopes", "exactly k correct matches"],
    unsafeWhen: ["Assignments permit multiple objects per destination."],
    archetypes: [archetype("probability", "matching fixed points")],
    difficulty: [4, 5],
  }),
  pilot({
    id: P.inverseComposition,
    chapter: "probability",
    title: "Infer a population composition from a draw probability",
    objective: "Invert a without-replacement probability expression to determine which integer population compositions are consistent with the evidence.",
    sourceIdeas: [],
    bankEvidence: "seed question 501",
    prerequisites: [P.withoutReplacement, A.integerConstraints],
    boundaries: ["Population counts are integer and bounded by the known total."],
    edgeCases: ["A probability may correspond to more than one feasible composition unless monotonicity or a second constraint resolves it."],
    confusables: [P.restricted],
    procedure: ["Name the unknown favorable count.", "Write the conditional product from that count and the total.", "Solve or enumerate the bounded integer equation.", "Check every feasible composition before declaring uniqueness."],
    cues: ["probability of two selected items is given; infer how many items of a type"],
    unsafeWhen: ["Treating a continuous algebraic root as valid without integer and bound checks."],
    archetypes: [archetype("probability", "inverse composition")],
    difficulty: [4, 5],
  }),
  pilot({
    id: P.stoppingTime,
    chapter: "probability",
    title: "Compute a finite stopping-time event",
    objective: "Enumerate the disjoint paths that cause a repeated process to stop at an event time with a finite cap.",
    sourceIdeas: [],
    bankEvidence: "seed question 502",
    prerequisites: [P.independent, P.complement],
    boundaries: ["The process ends at the first success or at the stated cap, so later outcomes do not exist on shorter paths."],
    edgeCases: ["Reaching the cap can include success or failure on the final trial, depending on how the event is worded."],
    confusables: [P.exactK],
    procedure: ["List each possible stopping time.", "Translate the target into allowed stopping times.", "Write the exact prefix path for each.", "Add the disjoint path probabilities."],
    cues: ["until first success or at most n trials", "probability the process lasts an even number of trials"],
    unsafeWhen: ["Multiplying by outcomes that occur after the process would already have stopped."],
    archetypes: [archetype("probability", "finite stopping time")],
    difficulty: [4, 5],
  }),
] as const;

export const PILOT_SOURCE_ASSIGNMENTS: Readonly<Record<string, string>> = Object.fromEntries(
  PILOT_CONCEPTS.flatMap((concept) =>
    concept.sourceCoreIdeaIds.map((sourceId) => [sourceId, concept.id] as const),
  ),
);

export const PILOT_CANONICAL_SOURCE_IDS = new Set(
  PILOT_CONCEPTS.flatMap((concept) => concept.sourceCoreIdeaIds.slice(0, 1)),
);

export const PILOT_SURFACE_IDS = { archetype, surface } as const;
